version: "3.7"

services:

  sonarqube:
    container_name: sonarqube79
    image: sonarqube:7.9.2-community
    ports:
    - 9000:9000
    restart: unless-stopped
    volumes:
    - ./conf:/opt/sonarqube/conf
    - ./extensions:/opt/sonarqube/extensions
    - ./logs:/opt/sonarqube/logs
    - ./data:/opt/sonarqube/data
